// RISC-V RV32I Core Testbench
// Generated by: Claude (LLM reasoning layer)
// Verified by: ChipAgent (MCP tools)

`timescale 1ns / 1ps

module riscv_core_tb;

    reg clk;
    reg rst_n;
    reg stall;

    wire [31:0] imem_addr;
    wire [31:0] imem_rdata;
    wire [31:0] dmem_addr;
    wire [31:0] dmem_wdata;
    wire [3:0]  dmem_we;
    wire [31:0] dmem_rdata;
    wire valid;

    // Instruction memory (1KB)
    reg [31:0] imem [0:255];

    // Data memory (1KB)
    reg [31:0] dmem [0:255];

    // DUT instantiation
    riscv_core dut (
        .clk(clk),
        .rst_n(rst_n),
        .imem_addr(imem_addr),
        .imem_rdata(imem_rdata),
        .dmem_addr(dmem_addr),
        .dmem_wdata(dmem_wdata),
        .dmem_we(dmem_we),
        .dmem_rdata(dmem_rdata),
        .stall(stall),
        .valid(valid)
    );

    // Clock generation (100MHz)
    initial begin
        clk = 0;
        forever #5 clk = ~clk;
    end

    // Memory read logic
    assign imem_rdata = imem[imem_addr[9:2]];
    assign dmem_rdata = dmem[dmem_addr[9:2]];

    // Memory write logic
    always @(posedge clk) begin
        if (dmem_we[0]) dmem[dmem_addr[9:2]][7:0] <= dmem_wdata[7:0];
        if (dmem_we[1]) dmem[dmem_addr[9:2]][15:8] <= dmem_wdata[15:8];
        if (dmem_we[2]) dmem[dmem_addr[9:2]][23:16] <= dmem_wdata[23:16];
        if (dmem_we[3]) dmem[dmem_addr[9:2]][31:24] <= dmem_wdata[31:24];
    end

    // Test program
    initial begin
        // Initialize memory
        $readmemh("test_program.hex", imem);

        // Reset
        rst_n = 0;
        stall = 0;
        #20;
        rst_n = 1;

        // Run for 100 cycles
        #1000;

        // Check results
        $display("Test Results:");
        $display("x1 = %h (expected: 00000005)", dut.regfile[1]);
        $display("x2 = %h (expected: 0000000A)", dut.regfile[2]);
        $display("x3 = %h (expected: 0000000F)", dut.regfile[3]);

        if (dut.regfile[1] == 32'h00000005 &&
            dut.regfile[2] == 32'h0000000A &&
            dut.regfile[3] == 32'h0000000F) begin
            $display("PASS: All tests passed!");
        end else begin
            $display("FAIL: Test failed!");
        end

        $finish;
    end

    // Timeout watchdog
    initial begin
        #2000;
        $display("ERROR: Simulation timeout!");
        $finish;
    end

    // VCD dump
    initial begin
        $dumpfile("riscv_core.vcd");
        $dumpvars(0, riscv_core_tb);
    end

endmodule
