// RISC-V RV32I Single-Cycle CPU Core
// Generated by: Claude (LLM reasoning layer)
// Verified by: ChipAgent (MCP tools)
//
// Features:
// - RV32I base instruction set
// - Single-cycle implementation (for demonstration)
// - Harvard architecture (separate instruction and data memory)
// - AXI4-Lite compatible bus interface
//
// Instructions supported:
// - R-type: ADD, SUB, SLL, SLT, SLTU, XOR, SRL, SRA, OR, AND
// - I-type: ADDI, SLTI, SLTIU, XORI, ORI, ANDI, SLLI, SRLI, SRAI
// - Load: LB, LH, LW, LBU, LHU
// - Store: SB, SH, SW
// - Branch: BEQ, BNE, BLT, BGE, BLTU, BGEU
// - Jump: JAL, JALR
// - Upper immediate: LUI, AUIPC
// - System: ECALL, EBREAK

module riscv_core (
    input  wire        clk,
    input  wire        rst_n,

    // Instruction memory interface
    output wire [31:0] imem_addr,
    input  wire [31:0] imem_rdata,

    // Data memory interface
    output wire [31:0] dmem_addr,
    output wire [31:0] dmem_wdata,
    output wire [3:0]  dmem_we,      // Byte write enable
    input  wire [31:0] dmem_rdata,

    // Control signals
    input  wire        stall,
    output wire        valid
);

    // Program Counter
    reg [31:0] pc;
    wire [31:0] pc_next;
    wire [31:0] pc_plus4;

    assign pc_plus4 = pc + 32'd4;
    assign imem_addr = pc;

    // Instruction decode
    wire [31:0] instr = imem_rdata;
    wire [6:0]  opcode = instr[6:0];
    wire [4:0]  rd = instr[11:7];
    wire [2:0]  funct3 = instr[14:12];
    wire [4:0]  rs1 = instr[19:15];
    wire [4:0]  rs2 = instr[24:20];
    wire [6:0]  funct7 = instr[31:25];

    // Immediate generation
    wire [31:0] imm_i = {{20{instr[31]}}, instr[31:20]};
    wire [31:0] imm_s = {{20{instr[31]}}, instr[31:25], instr[11:7]};
    wire [31:0] imm_b = {{19{instr[31]}}, instr[31], instr[7], instr[30:25], instr[11:8], 1'b0};
    wire [31:0] imm_u = {instr[31:12], 12'b0};
    wire [31:0] imm_j = {{11{instr[31]}}, instr[31], instr[19:12], instr[20], instr[30:21], 1'b0};

    // Register file
    reg [31:0] regfile [0:31];
    wire [31:0] rs1_data = (rs1 == 5'd0) ? 32'd0 : regfile[rs1];
    wire [31:0] rs2_data = (rs2 == 5'd0) ? 32'd0 : regfile[rs2];

    // Instruction type decode
    wire is_r_type = (opcode == 7'b0110011);
    wire is_i_type = (opcode == 7'b0010011) || (opcode == 7'b0000011) || (opcode == 7'b1100111);
    wire is_s_type = (opcode == 7'b0100011);
    wire is_b_type = (opcode == 7'b1100011);
    wire is_u_type = (opcode == 7'b0110111) || (opcode == 7'b0010111);
    wire is_j_type = (opcode == 7'b1101111);

    // ALU control
    wire [31:0] alu_op1, alu_op2;
    wire [3:0] alu_ctrl;

    assign alu_op1 = rs1_data;
    assign alu_op2 = is_i_type ? imm_i : (is_s_type ? imm_s : rs2_data);

    // ALU control logic
    reg [3:0] alu_ctrl_reg;
    always @(*) begin
        case (opcode)
            7'b0110011: begin // R-type
                case (funct3)
                    3'b000: alu_ctrl_reg = (funct7[5]) ? 4'b1001 : 4'b0000; // SUB or ADD
                    3'b001: alu_ctrl_reg = 4'b0001; // SLL
                    3'b010: alu_ctrl_reg = 4'b0010; // SLT
                    3'b011: alu_ctrl_reg = 4'b0011; // SLTU
                    3'b100: alu_ctrl_reg = 4'b0100; // XOR
                    3'b101: alu_ctrl_reg = (funct7[5]) ? 4'b1011 : 4'b0101; // SRA or SRL
                    3'b110: alu_ctrl_reg = 4'b0110; // OR
                    3'b111: alu_ctrl_reg = 4'b0111; // AND
                    default: alu_ctrl_reg = 4'b0000;
                endcase
            end
            7'b0010011: begin // I-type ALU
                case (funct3)
                    3'b000: alu_ctrl_reg = 4'b0000; // ADDI
                    3'b001: alu_ctrl_reg = 4'b0001; // SLLI
                    3'b010: alu_ctrl_reg = 4'b0010; // SLTI
                    3'b011: alu_ctrl_reg = 4'b0011; // SLTIU
                    3'b100: alu_ctrl_reg = 4'b0100; // XORI
                    3'b101: alu_ctrl_reg = (funct7[5]) ? 4'b1011 : 4'b0101; // SRAI or SRLI
                    3'b110: alu_ctrl_reg = 4'b0110; // ORI
                    3'b111: alu_ctrl_reg = 4'b0111; // ANDI
                    default: alu_ctrl_reg = 4'b0000;
                endcase
            end
            7'b0000011: alu_ctrl_reg = 4'b0000; // Load (ADD for address)
            7'b0100011: alu_ctrl_reg = 4'b0000; // Store (ADD for address)
            7'b0010111: alu_ctrl_reg = 4'b0000; // AUIPC (ADD)
            default: alu_ctrl_reg = 4'b0000;
        endcase
    end
    assign alu_ctrl = alu_ctrl_reg;

    // ALU
    reg [31:0] alu_result;
    reg alu_zero, alu_less;

    always @(*) begin
        case (alu_ctrl)
            4'b0000: begin alu_result = alu_op1 + alu_op2; alu_less = 1'b0; end // ADD
            4'b1001: begin alu_result = alu_op1 - alu_op2; alu_less = 1'b0; end // SUB
            4'b0001: begin alu_result = alu_op1 << alu_op2[4:0]; alu_less = 1'b0; end // SLL
            4'b0010: begin alu_result = {31'b0, $signed(alu_op1) < $signed(alu_op2)}; alu_less = ($signed(alu_op1) < $signed(alu_op2)); end // SLT
            4'b0011: begin alu_result = {31'b0, alu_op1 < alu_op2}; alu_less = (alu_op1 < alu_op2); end // SLTU
            4'b0100: begin alu_result = alu_op1 ^ alu_op2; alu_less = 1'b0; end // XOR
            4'b0101: begin alu_result = alu_op1 >> alu_op2[4:0]; alu_less = 1'b0; end // SRL
            4'b1011: begin alu_result = $signed(alu_op1) >>> alu_op2[4:0]; alu_less = 1'b0; end // SRA
            4'b0110: begin alu_result = alu_op1 | alu_op2; alu_less = 1'b0; end // OR
            4'b0111: begin alu_result = alu_op1 & alu_op2; alu_less = 1'b0; end // AND
            default: begin alu_result = 32'b0; alu_less = 1'b0; end
        endcase
        alu_zero = (alu_result == 32'b0);
    end

    // Branch logic
    wire branch_taken;
    wire [31:0] branch_target;

    assign branch_target = pc + imm_b;

    reg branch_taken_reg;
    always @(*) begin
        if (is_b_type) begin
            case (funct3)
                3'b000: branch_taken_reg = (rs1_data == rs2_data); // BEQ
                3'b001: branch_taken_reg = (rs1_data != rs2_data); // BNE
                3'b100: branch_taken_reg = ($signed(rs1_data) < $signed(rs2_data)); // BLT
                3'b101: branch_taken_reg = ($signed(rs1_data) >= $signed(rs2_data)); // BGE
                3'b110: branch_taken_reg = (rs1_data < rs2_data); // BLTU
                3'b111: branch_taken_reg = (rs1_data >= rs2_data); // BGEU
                default: branch_taken_reg = 1'b0;
            endcase
        end else begin
            branch_taken_reg = 1'b0;
        end
    end
    assign branch_taken = branch_taken_reg;

    // Jump logic
    wire jump_taken;
    wire [31:0] jump_target;

    assign jump_taken = (opcode == 7'b1101111) || (opcode == 7'b1100111); // JAL or JALR
    assign jump_target = (opcode == 7'b1101111) ? (pc + imm_j) : ((rs1_data + imm_i) & 32'hFFFFFFFE);

    // Memory access
    wire mem_read = (opcode == 7'b0000011);
    wire mem_write = (opcode == 7'b0100011);
    wire [31:0] mem_addr = alu_result;

    // Load data alignment
    reg [31:0] load_data;
    always @(*) begin
        case (funct3)
            3'b000: load_data = {{24{dmem_rdata[7]}}, dmem_rdata[7:0]}; // LB
            3'b001: load_data = {{16{dmem_rdata[15]}}, dmem_rdata[15:0]}; // LH
            3'b010: load_data = dmem_rdata; // LW
            3'b100: load_data = {24'b0, dmem_rdata[7:0]}; // LBU
            3'b101: load_data = {16'b0, dmem_rdata[15:0]}; // LHU
            default: load_data = dmem_rdata;
        endcase
    end

    // Write-back data
    wire [31:0] wb_data;
    wire wb_en;

    assign wb_en = (rd != 5'd0) && (is_r_type || is_i_type || is_u_type || is_j_type || mem_read);
    assign wb_data = mem_read ? load_data :
                     (opcode == 7'b0110111) ? imm_u : // LUI
                     (opcode == 7'b0010111) ? (pc + imm_u) : // AUIPC
                     (opcode == 7'b1101111 || opcode == 7'b1100111) ? pc_plus4 : // JAL/JALR
                     alu_result;

    // Next PC logic
    assign pc_next = jump_taken ? jump_target :
                     branch_taken ? branch_target :
                     pc_plus4;

    // PC update
    always @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            pc <= 32'h00000000;
        end else if (!stall) begin
            pc <= pc_next;
        end
    end

    // Register file write
    always @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            // Reset all registers to 0
            integer i;
            for (i = 0; i < 32; i = i + 1) begin
                regfile[i] <= 32'd0;
            end
        end else if (wb_en) begin
            regfile[rd] <= wb_data;
        end
    end

    // Data memory interface
    assign dmem_addr = mem_addr;
    assign dmem_wdata = rs2_data;

    reg [3:0] dmem_we_reg;
    always @(*) begin
        if (mem_write) begin
            case (funct3[1:0])
                2'b00: dmem_we_reg = 4'b0001; // SB
                2'b01: dmem_we_reg = 4'b0011; // SH
                2'b10: dmem_we_reg = 4'b1111; // SW
                default: dmem_we_reg = 4'b0000;
            endcase
        end else begin
            dmem_we_reg = 4'b0000;
        end
    end
    assign dmem_we = dmem_we_reg;

    // Valid output
    assign valid = 1'b1;

endmodule
