//------------------------------------------------------------
// Module : {{module_name}}
// Purpose: Minimal registered data-path scaffold generated by ChipAgent.
// Interface: {{interface}}
// Data width: {{data_width}} bits
// Clocking: {{clocking_desc}}
// Behaviour: reset -> zero outputs; else forward data_in, assert valid.
//------------------------------------------------------------
module {{module_name}} (
{{#if clock}}    input  logic clk,                        // clock, rising-edge
{{/if}}{{#if reset}}    input  logic rst_n,                      // active-low asynchronous reset
{{/if}}    input  logic [{{data_width_m1}}:0] data_in,   // {{data_width}}-bit data input
    output logic [{{data_width_m1}}:0] data_out,  // {{data_width}}-bit registered data output
    output logic valid                         // data_out is valid this cycle
);
    // Registered data path: on reset clear outputs, otherwise
    // forward data_in to data_out and assert valid.
{{#if reset}}
    always_ff @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            data_out <= '0;
            valid   <= 1'b0;
        end else begin
            data_out <= data_in;
            valid   <= 1'b1;
        end
    end
{{/if}}{{#if clock_no_reset}}
    always_ff @(posedge clk) begin
        data_out <= data_in;
        valid   <= 1'b1;
    end
{{/if}}{{#if combinational}}
    assign data_out = data_in;
    assign valid = 1'b1;
{{/if}}
endmodule
